### ISSUE TITLE
"Unauthorized" error is thrown when ReminderApi().list() is executed

### ISSUE THREAD

**Issue by ranjjose-chaz** [windmark/google-reminder-api-wrapper#2]
```
>>> from google_reminder_api_wrapper import ReminderApi
>>> api = ReminderApi()
>>> reminders = api.list()
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    reminders = api.list()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_reminder_api_wrapper/reminder_api.py", line 29, in list
    return self.request('list', '')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_reminder_api_wrapper/reminder_api_base.py", line 46, in request
    raise Exception(res.reason, res.text)
Exception: ('Unauthorized', '{\n  "error": {\n    "code": 401,\n    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "status": "UNAUTHENTICATED"\n  }\n}\n')
```

**Comment by darkzbaron** [comment]
How did you solve this?

**Comment by ffollett** [comment]
@ranjjose-chaz Did you resolve this issue?  I just installed and am getting the exact same error.  I've tried double checking my environment variables, but I'm pretty sure everything is set correctly.
